font_family JetBrains Mono Nerd Font
font_size 9
shell_integration no-rc

background_opacity 0.5
confirm_os_window_close 0
cursor_trail 10
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 0
dynamic_background_opacity yes
scrollback_lines 10000
update_check_interval 0
window_padding_width 10

include current-theme.conf
# include /home/Aftical/.cache/wal/colors-kitty.conf

cursor_shape underline
cursor_underline_thickness 1
sync_to_monitor yes

color0 #17120f
color1 #ffb4ab
color2 #ffb780
color3 #e4bfa7
color4 #c6ca95
color5 #ffb780
color6 #e4bfa7
color7 #ece0da
color8 #9f8d82
color9 #ffb4ab
color10 #ffb780
color11 #e4bfa7
color12 #c6ca95
color13 #ffb780
color14 #e4bfa7
color15 #ece0da

cursor                #ece0da
cursor_text_color     #17120f
background            #17120f
foreground            #ece0da
selection_foreground  #d6c3b7
selection_background  #51443b
active_border_color   #ffb780
inactive_border_color #51443b
url_color             #ffb780

active_tab_foreground   #4e2600
active_tab_background   #ffb780
inactive_tab_foreground #d6c3b7
inactive_tab_background #51443b
cursor_trail_color      #d6c3b7
