hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 16")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("kwybars-daemon")
	hl.exec_cmd("waybar")
	hl.exec_cmd("dunst")
	hl.exec_cmd('mpvpaper -vsf -o "no-audio loop" eDP-1 ~/.config/Aftical-dot/aniwall/"Blue Archive - Momoi (Maid) Live2D [t6n5DyvGF8Y] 768p.webm"')
	hl.exec_cmd("~/.config/Aftical-dot/shell-sh/notify.sh")
	-- hl.exec_cmd("qs -c noctalia-shell")
	-- hl.exec_cmd("foot --server")
end)
hl.env("XCURSOR_SIZE", "16")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "16")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
