hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 16")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("kwybars-daemon")
	-- hl.exec_cmd("foot --server")
	hl.exec_cmd("waybar")
	hl.exec_cmd('mpvpaper -vs -o "no-audio loop" eDP-1 ~/asset/lobby.webm')
	hl.exec_cmd("~/.config/Aftical-dot/shell-sh/notify.sh")
	-- hl.exec_cmd("qs -c noctalia-shell")
end)
hl.env("XCURSOR_SIZE", "16")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "16")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
