local terminal = "kitty"
local fileManager = "thunar"
-- local menu = "qs -c noctalia-shell ipc call launcher toggle"
-- local setting = "qs -c noctalia-shell ipc call settings toggle"
-- local wallpaper = "qs -c noctalia-shell ipc call wallpaper toggle"
-- local session = "qs -c noctalia-shell ipc call sessionMenu toggle"
-- local controlCenter = "qs -c noctalia-shell ipc call controlCenter toggle"
-- local clipboard = "qs -c noctalia-shell ipc call launcher clipboard"
-- hl.bind("SUPER + Return", hl.dsp.exec_cmd("~/.config/Aftical-dot/shell-sh/anip.sh"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty --app-id float"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + CTRL + SHIFT + Q", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("kitty --app-id float yazi"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("kitty --app-id editor nvim"))
hl.bind("SUPER + PRINT", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("SUPER + SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind("SUPER + Z", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + CTRL + Escape", hl.dsp.exec_cmd("kitty btop"))
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("kitty ncmpcpp"))
hl.bind("F12", hl.dsp.exec_cmd("~/.config/Aftical-dot/shell-sh/notify.sh"))
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("~/.config/Aftical-dot/shell-sh/way-re.sh"))
hl.bind("SUPER + SUPER_L ", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind("SUPER +  ESCAPE", hl.dsp.exec_cmd("wlogout"))
-- hl.bind("SUPER + SUPER_L ", hl.dsp.exec_cmd(menu))
-- hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd(wallpaper))
-- hl.bind("SUPER + V", hl.dsp.exec_cmd(clipboard))
-- hl.bind("SUPER + Escape", hl.dsp.exec_cmd(session))
-- hl.bind("SUPER + SHIFT + comma", hl.dsp.exec_cmd(setting))
-- hl.bind("SUPER + comma", hl.dsp.exec_cmd(controlCenter))
hl.bind("SUPER + h", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + j", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + k", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + l", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + M", hl.dsp.workspace.toggle_special("magic ncmpcpp"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + H", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true }	)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("mpc next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("mpc toggle"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("mpc toggle"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("mpc prev"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("SUPER + F1", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true })
hl.bind("SUPER + F2", hl.dsp.exec_cmd("brightnessctl set +5%"), { repeating = true })
hl.bind("SUPER + F3", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeat_press = false })
hl.bind("SUPER + F4", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { repeat_press = false })
hl.bind("SUPER + F5", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("SUPER + F6", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("SUPER + F7", hl.dsp.exec_cmd("playerctl next"))
hl.bind("SUPER + F5", hl.dsp.exec_cmd("mpc prev"))
hl.bind("SUPER + F6", hl.dsp.exec_cmd("mpc toggle"))
hl.bind("SUPER + F7", hl.dsp.exec_cmd("mpc next"))
for i = 1, 10 do
	local key = i % 10
	hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
